CREATE TABLE tb_evento_saude
(
    id          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id      NUMBER(38, 0)                                  NOT NULL,
    tipo_evento VARCHAR2(255)                                  NOT NULL,
    descricao   VARCHAR2(255)                                  NOT NULL,
    data_evento date NOT NULL,
    CONSTRAINT pk_tb_evento_saude PRIMARY KEY (id)
);

CREATE TABLE tb_pet
(
    id           NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR2(100)                                  NOT NULL,
    especie      VARCHAR2(50)                                   NOT NULL,
    raca         VARCHAR2(50),
    idade        INTEGER          NOT NULL,
    peso         DOUBLE PRECISION NOT NULL,
    health_score INTEGER          NOT NULL,
    tutor_id     NUMBER(38, 0)                                  NOT NULL,
    CONSTRAINT pk_tb_pet PRIMARY KEY (id)
);

CREATE TABLE tb_tutor
(
    id       NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR2(100)                                  NOT NULL,
    email    VARCHAR2(100)                                  NOT NULL,
    telefone VARCHAR2(20)                                   NOT NULL,
    perfil   NUMBER(5)                                      NOT NULL,
    CONSTRAINT pk_tb_tutor PRIMARY KEY (id)
);

ALTER TABLE tb_tutor
    ADD CONSTRAINT uc_tb_tutor_email UNIQUE (email);

ALTER TABLE tb_evento_saude
    ADD CONSTRAINT FK_TB_EVENTO_SAUDE_ON_PET FOREIGN KEY (pet_id) REFERENCES tb_pet (id);

ALTER TABLE tb_pet
    ADD CONSTRAINT FK_TB_PET_ON_TUTOR FOREIGN KEY (tutor_id) REFERENCES tb_tutor (id);