ALTER TABLE TB_TUTOR ADD PERFIL_NOVO VARCHAR2(20);

UPDATE TB_TUTOR
SET PERFIL_NOVO =
        CASE PERFIL
            WHEN 0 THEN 'TUTOR'
            WHEN 1 THEN 'VETERINARIO'
            ELSE 'TUTOR'
            END;

ALTER TABLE TB_TUTOR DROP COLUMN PERFIL;

ALTER TABLE TB_TUTOR RENAME COLUMN PERFIL_NOVO TO PERFIL;

ALTER TABLE TB_TUTOR
    MODIFY PERFIL VARCHAR2(20) DEFAULT 'TUTOR' NOT NULL;